title: "Aung Phone Myat"
description: "Writing on engineering, music, and music therapy."
theme: minima
show_excerpts: true
timezone: Asia/Yangon
author: "Aung Phone Myat"

# --- URL Settings ---
url: "https://aungphonemyat.github.io"  # no trailing slash
baseurl: ""  # leave empty for user site (e.g., username.github.io)

# --- Default Social Image ---
logo: /assets/img/cover.jpg  # must exist; best size = 1200x630

# --- Navigation / Social Links ---
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/eric9435" }

# --- Plugins (for GitHub Pages SEO, sitemap, feed, etc.) ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# --- Pagination ---
paginate: 6
paginate_path: "/page:num/"

# --- Include folders for build ---
include:
  - assets
  - _includes
  - engineering/acmv/_posts

google_analytics: G-B77C04H7TZ
